### ISSUE TITLE
Deprecation?

### ISSUE THREAD

**Issue by georgefst** [bgamari/linux-evdev#7]
So eventually, after struggling with #3, I ended writing [my own library](http://hackage.haskell.org/package/evdev).

It's now pretty stable, and offers a superset of the functionality that this one does (plus I'm planning to finish `uinput` support in the next day or two). It is slightly higher-level, and also has more documentation.

Obviously, this can be a sensitive issue. But I sense you have no strong attachment to this library, and I know you've had many far more important things to work on in the few years since this library last received a significant update. So, I was wondering if you might want to spare yourself the maintenance burden and point people over there instead?

**Comment by bgamari** [comment]
Indeed, that would be fine. Merge requests accepted.

**Comment by georgefst** [comment]
IMO, the simplest thing would be to edit the description bar on GitHub, since there's currently no README. I don't believe I can influence that through a MR.

And if you did wish to mark as deprecated on Hackage, that's easiest (or only possible?) through the package's 'Maintainer's Corner'.

**Comment by bgamari** [comment]
Marked as deprecated on Hackage.

**Comment by bgamari** [comment]
1.
